#!/bin/bash -l

#SBATCH --account llm-degredation --partition tier3
#SBATCH -n 1
#SBATCH -c 8
#SBATCH --gres=gpu:a100:1
#SBATCH --mem=50g
#SBATCH --job-name=fedllm
#SBATCH --output=/shared/rc/llm-degredation/logs/log6.out
#SBATCH --error=/shared/rc/llm-degredation/logs/log6.err

export HUGGINGFACE_HUB_TOKEN='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'
# module purge
# conda activate fedllmold


max_steps=10
num_rounds=50
batch_size=16
gradient_accumulation_steps=1
seq_length=512
sample_clients=1
lora_r=32
lora_alpha=64   # twice of lora_r
lr=5e-5

num_data_per_client=500
local_data_dir="gen_data"       # you may set your local data directory

# Level 1 Defense: use public harmless data
# Level 2 Defense: use harmless and helpful data generated by Mistral
# Level 3 Defense: use harmless and helpful data generated by trained model itself
benign_num_clients=(1)
# benign_dataset_names=("purebad") # Level 2 Defense;
# benign_dataset_names=($finetuning_dataset)
benign_dataset_names=("MaliciousGen") # Level 2 Defense;

thrss=(0.15 0.2 0.25)

malicious_num_clients=(0)
malicious_dataset_names=("_")
# existing_lora="/shared/rc/llm-degredation/fedllm/barebones/squad_v27_BeaverTails3_500_fedavg_c10s10_i10_b16a1_l512_r32a64_20251201105506"
# existing_lora="/shared/rc/llm-degredation/fedllm/barebones/PubMedQA7_BeaverTails3_500_fedavg_c10s10_i10_b16a1_l512_r32a64_20251201105050"

# existing_lora="/shared/rc/llm-degredation/fedllm/barebones/PubMedQA7_BeaverTails3_500_fedavg_c10s10_i10_b16a1_l512_r32a64_20251201105050"

# existing_lora="/shared/rc/llm-degredation/fedllm/barebones/squad_v27_BeaverTails3_500_fedavg_c10s10_i10_b16a1_l512_r32a64_20251201105506"

# existing_lora="/shared/rc/llm-degredation/fedllm/barebones/medQA7_BeaverTails3_500_fedavg_c10s10_i10_b16a1_l512_r32a64_20251203103114"
# existing_lora="/shared/rc/llm-degredation/fedllm/barebones/squad_v24_PubMedQA4_BeaverTails4_500_fedavg_c12s12_i10_b16a1_l512_r32a64_20251208190322"
# model_name_or_path="meta-llama/Llama-2-7b-chat-hf" # BASE MODEL PATH
model_name_or_path='Qwen/Qwen2.5-7B-Instruct'
# model_name_or_path="meta-llama/Llama-3.1-8B-Instruct"
# model_name_or_path="google/gemma-2-2b-it"
# model_name_or_path="meta-llama/Llama-2-7b-chat-hf" # BASE MODEL PATH
output_dir='/scratch/ps9044/'
# existing_lora='/shared/rc/llm-degredation/fedllm/barebones/PubMedQA3_squad_v23_BeaverTails3_500_fedavg_c9s10_i5_b16a1_l512_r32a64_20260130234337'
# existing_lora='/scratch/ps9044/newsetting/PubMedQA7_BeaverTails3_500_fedavg_c10s10_i10_b16a1_l512_r64a128_20260218190209'
# existing_lora='/scratch/ps9044/newsetting/PubMedQA7_BeaverTails3_500_fedavg_c10s10_i10_b16a1_l512_r128a256_20260219071754'
# existing_lora='/scratch/ps9044/newsetting/PubMedQA7_BeaverTails3_500_fedavg_c10s10_i10_b16a1_l512_r32a64_20260212154647'
gpu=4
fed_alg="fedavg"




CUDA_VISIBLE_DEVICES=$gpu python main_sft.py \
 --learning_rate $lr \
 --model_name_or_path $model_name_or_path \
 --local_data_dir $local_data_dir \
 --benign_num_clients ${benign_num_clients[@]} \
 --benign_dataset_names ${benign_dataset_names[@]} \
 --malicious_num_clients ${malicious_num_clients[@]} \
 --malicious_dataset_names ${malicious_dataset_names[@]} \
 --num_data_per_client $num_data_per_client \
 --fed_alg $fed_alg \
 --sample_clients $sample_clients \
 --max_steps $max_steps \
 --num_rounds $num_rounds \
 --batch_size $batch_size \
 --gradient_accumulation_steps $gradient_accumulation_steps \
 --seq_length $seq_length \
 --peft_lora_r $lora_r \
 --peft_lora_alpha $lora_alpha \
 --use_peft \
 --load_in_8bit \
 --output_dir $output_dir \
 --template "chat" \
#  --existing_lora $existing_lora \


