max_steps=10
num_rounds=50
batch_size=16
gradient_accumulation_steps=1
seq_length=512
sample_clients=1
lora_r=32
lora_alpha=64   # twice of lora_r
lr=5e-5

num_data_per_client=1000
local_data_dir="gen_data"       # you may set your local data directory

# Level 1 Defense: use public harmless data
# Level 2 Defense: use harmless and helpful data generated by Mistral
# Level 3 Defense: use harmless and helpful data generated by trained model itself
benign_num_clients=(1)
benign_dataset_names=("MaliciousGen") # Level 2 Defense;

malicious_num_clients=(0)
malicious_dataset_names=("_")

existing_lora="/scratch/ps9044/fedllm/barebones/WildChat7_BeaverTails3_500_fedavg_c10s3_i10_b16a1_l512_r32a64_20251020143720" # Trained Model Dir
model_name_or_path="meta-llama/Llama-2-7b-chat-hf" # BASE MODEL PATH
output_dir='/scratch/ps9044/fedllm/safelora_maliciousgen_llama27bchat'

gpu=5
fed_alg="fedavg"

CUDA_VISIBLE_DEVICES=$gpu python main_sft.py \
 --existing_lora $existing_lora \
 --learning_rate $lr \
 --model_name_or_path $model_name_or_path \
 --local_data_dir $local_data_dir \
 --benign_num_clients ${benign_num_clients[@]} \
 --benign_dataset_names ${benign_dataset_names[@]} \
 --malicious_num_clients ${malicious_num_clients[@]} \
 --malicious_dataset_names ${malicious_dataset_names[@]} \
 --num_data_per_client $num_data_per_client \
 --fed_alg $fed_alg \
 --sample_clients $sample_clients \
 --max_steps $max_steps \
 --num_rounds $num_rounds \
 --batch_size $batch_size \
 --gradient_accumulation_steps $gradient_accumulation_steps \
 --seq_length $seq_length \
 --peft_lora_r $lora_r \
 --peft_lora_alpha $lora_alpha \
 --use_peft \
 --load_in_8bit \
 --output_dir $output_dir \
 --template "alpaca" \